services:

  uwsgi:
    build: .
    ports:
      - "8101:8101"
    volumes:
      - .:/app
    links:
      - nginx
    depends_on:
      - nginx
    command: make run-uwsgi
    environment:
      PORT: 8101

  fastapi:
    build: .
    ports:
      - "8102:8102"
    volumes:
      - .:/app
    links:
      - nginx
    depends_on:
      - nginx
    command: make run-fastapi
    environment:
      PORT: 8102

  aiohttp:
    build: .
    ports:
      - "8103:8103"
    volumes:
      - .:/app
    links:
      - nginx
    depends_on:
      - nginx
    command: make run-aiohttp
    environment:
      PORT: 8103
      LOOP_POLICY: uvloop.EventLoopPolicy

  fastapi-hypercorn:
    build: .
    ports:
      - "8104:8104"
    volumes:
      - .:/app
    links:
      - nginx
    depends_on:
      - nginx
    command: make run-fastapi-hypercorn
    environment:
      PORT: 8104

  sanic-direct:
    build: .
    ports:
      - "8105:8105"
    volumes:
      - .:/app
    links:
      - nginx
    depends_on:
      - nginx
    command: make run-sanic-direct
    environment:
      PORT: 8105

  sanic-asgi:
    build: .
    ports:
      - "8106:8106"
    volumes:
      - .:/app
    links:
      - nginx
    depends_on:
      - nginx
    command: make run-sanic-asgi
    environment:
      PORT: 8106

  starlette-uvicorn:
    build: .
    ports:
      - "8107:8107"
    volumes:
      - .:/app
    links:
      - nginx
    depends_on:
      - nginx
    command: make run-starlette-uvicorn
    environment:
      PORT: 8107

  nginx:
    image: nginx
    logging:
      driver: none
    volumes:
      - ./fixtures/:/usr/share/nginx/html:ro
    ports:
      - "8100:80"
