services:

  uwsgi:
    build: .
    ports:
      - "8101:8101"
    volumes:
      - .:/app
    links:
      - nginx
    depends_on:
      - nginx
    command: make run-uwsgi

  fastapi:
    build: .
    ports:
      - "8102:8102"
    volumes:
      - .:/app
    links:
      - nginx
    depends_on:
      - nginx
    command: make run-fastapi

  nginx:
    image: nginx
    logging:
      driver: none
    volumes:
      - ./fixtures/:/usr/share/nginx/html:ro
    ports:
      - "8100:80"
